[package]
name = "systray-rs-ti"
version = "0.1.0"
authors = ["vadym <vadym.vikulin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
